# Generated by Django 6.0 on 2025-12-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('page_url', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('intent_level', models.CharField(default='LOW', max_length=20)),
                ('flipkart_clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
